### ISSUE TITLE
Could the slides be open sourced?

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets-tutorial#12]
I am hoping to introduce targets to my group and give a workshop for them. Is there any possibility to customize the slides a bit? Will keep the copyright notice.

**Comment by wlandau** [comment]
Awesome, please share! https://github.com/wlandau/targets-tutorial/blob/main/LICENSE.md describes the various sources and copyrights. Fine to copy with attribution.

Depending on your audience, you might also be interested in similar presentations https://github.com/wlandau/rpharma2020 and https://github.com/wlandau/nyhackr2020. The former is a simulations study of a COVID-19 clinical trial, and the latter is a Bayesian model validation exercise.

**Comment by liutiming** [comment]
Thanks!

Do you have the editable versions of the slides though?

**Comment by wlandau** [comment]
Sorry, didn't realize that's what you were asking. The main source file is at https://github.com/wlandau/targets-tutorial/blob/main/docs/index.Rmd. The other sources are at the top levels of the respective repos I linked.
